[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="potaudit"
version="1.0"

dependencies = [
    "ase",
]

[project.scripts]
potaudit = "potaudit.cli:main"
dpgen-fp = "potaudit.dpgen_fp:main"
dpgen-fp-converge = "potaudit.dpgen_fp_converge:main"

[tool.setuptools]
package-dir = {"" = "src"}
